void goodness_saturated_card_rhalphabet_all_2016_floatZ()
{
//=========Macro generated from canvas: goodness_saturated_card_rhalphabet_all_2016_floatZ/goodness_saturated_card_rhalphabet_all_2016_floatZ
//=========  (Sat Sep 14 05:59:40 2019) by ROOT version 6.12/07
   TCanvas *goodness_saturated_card_rhalphabet_all_2016_floatZ = new TCanvas("goodness_saturated_card_rhalphabet_all_2016_floatZ", "goodness_saturated_card_rhalphabet_all_2016_floatZ",0,0,800,600);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetHighLightColor(2);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->Range(-38.56989,-4.490096,282.8459,32.92737);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetFillColor(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetBorderMode(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetBorderSize(2);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetTickx(1);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetTicky(1);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetLeftMargin(0.12);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetBottomMargin(0.12);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetFrameFillStyle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetFrameBorderMode(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetFrameFillStyle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetFrameBorderMode(0);
   
   TH1F *goodness_saturated_card_rhalphabet_all_2016_floatZhist__1 = new TH1F("goodness_saturated_card_rhalphabet_all_2016_floatZhist__1","goodness_saturated_card_rhalphabet_all_2016_floatZhist",70,0,250.7043);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(17,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(18,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(19,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(20,5);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(21,7);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(22,5);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(23,11);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(24,13);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(25,21);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(26,12);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(27,23);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(28,19);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(29,23);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(30,9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(31,14);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(32,11);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(33,4);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(34,9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(35,3);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(36,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(37,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(40,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetBinContent(43,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetEntries(200);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetDirectory(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetStats(0);
   
   TF1 *chisqpdf1 = new TF1("chisqpdf","[0]*ROOT::Math::chisquared_pdf(x,[1])",0,250.7043, TF1::EAddToList::kNo);
   chisqpdf1->SetFillColor(19);
   chisqpdf1->SetFillStyle(0);
   chisqpdf1->SetMarkerStyle(20);
   chisqpdf1->SetLineColor(2);
   chisqpdf1->SetLineWidth(1);
   chisqpdf1->SetChisquare(25.34099);
   chisqpdf1->SetNDF(68);
   chisqpdf1->GetXaxis()->SetLabelFont(42);
   chisqpdf1->GetXaxis()->SetLabelOffset(0.007);
   chisqpdf1->GetXaxis()->SetLabelSize(0.05);
   chisqpdf1->GetXaxis()->SetTitleSize(0.06);
   chisqpdf1->GetXaxis()->SetTitleOffset(0.9);
   chisqpdf1->GetXaxis()->SetTitleFont(42);
   chisqpdf1->GetYaxis()->SetLabelFont(42);
   chisqpdf1->GetYaxis()->SetLabelOffset(0.007);
   chisqpdf1->GetYaxis()->SetLabelSize(0.05);
   chisqpdf1->GetYaxis()->SetTitleSize(0.06);
   chisqpdf1->GetYaxis()->SetTitleOffset(1.25);
   chisqpdf1->GetYaxis()->SetTitleFont(42);
   chisqpdf1->SetParameter(0,716.2739);
   chisqpdf1->SetParError(0,50.64822);
   chisqpdf1->SetParLimits(0,0,0);
   chisqpdf1->SetParameter(1,96.40293);
   chisqpdf1->SetParError(1,0.9767618);
   chisqpdf1->SetParLimits(1,0,0);
   chisqpdf1->SetParent(goodness_saturated_card_rhalphabet_all_2016_floatZhist__1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetListOfFunctions()->Add(chisqpdf1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetLineStyle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->SetMarkerStyle(20);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetTitle("-2log#lambda");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetTitleOffset(0.9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetXaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetTitle("Pseudodatasets");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetTitleOffset(0.85);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetYaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetZaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetZaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetZaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetZaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->GetZaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__1->Draw("pez");
   
   TH1F *goodness_saturated_card_rhalphabet_all_2016_floatZhist__2 = new TH1F("goodness_saturated_card_rhalphabet_all_2016_floatZhist__2","goodness_saturated_card_rhalphabet_all_2016_floatZhist",70,0,250.7043);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(34,9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(35,3);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(36,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(37,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(40,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetBinContent(43,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetEntries(18);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetStats(0);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = TColor::GetColor("#00ccff");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetFillColor(ci);

   ci = TColor::GetColor("#00ccff");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetLineColor(ci);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetLineStyle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->SetMarkerStyle(20);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetTitleOffset(0.9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetXaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetTitleOffset(1.25);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetYaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetZaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetZaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetZaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetZaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->GetZaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__2->Draw("histsame");
   
   TF1 *chisqpdf2 = new TF1("chisqpdf","[0]*ROOT::Math::chisquared_pdf(x,[1])",0,250.7043, TF1::EAddToList::kDefault);
   chisqpdf2->SetFillColor(19);
   chisqpdf2->SetFillStyle(0);
   chisqpdf2->SetMarkerStyle(20);
   chisqpdf2->SetLineColor(2);
   chisqpdf2->SetLineWidth(1);
   chisqpdf2->SetChisquare(25.34099);
   chisqpdf2->SetNDF(68);
   chisqpdf2->GetXaxis()->SetLabelFont(42);
   chisqpdf2->GetXaxis()->SetLabelOffset(0.007);
   chisqpdf2->GetXaxis()->SetLabelSize(0.05);
   chisqpdf2->GetXaxis()->SetTitleSize(0.06);
   chisqpdf2->GetXaxis()->SetTitleOffset(0.9);
   chisqpdf2->GetXaxis()->SetTitleFont(42);
   chisqpdf2->GetYaxis()->SetLabelFont(42);
   chisqpdf2->GetYaxis()->SetLabelOffset(0.007);
   chisqpdf2->GetYaxis()->SetLabelSize(0.05);
   chisqpdf2->GetYaxis()->SetTitleSize(0.06);
   chisqpdf2->GetYaxis()->SetTitleOffset(1.25);
   chisqpdf2->GetYaxis()->SetTitleFont(42);
   chisqpdf2->SetParameter(0,716.2739);
   chisqpdf2->SetParError(0,50.64822);
   chisqpdf2->SetParLimits(0,0,0);
   chisqpdf2->SetParameter(1,96.40293);
   chisqpdf2->SetParError(1,0.9767618);
   chisqpdf2->SetParLimits(1,0,0);
   chisqpdf2->Draw("same");
   
   TH1F *goodness_saturated_card_rhalphabet_all_2016_floatZhist__3 = new TH1F("goodness_saturated_card_rhalphabet_all_2016_floatZhist__3","goodness_saturated_card_rhalphabet_all_2016_floatZhist",70,0,250.7043);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(17,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(18,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(19,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(20,5);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(21,7);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(22,5);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(23,11);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(24,13);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(25,21);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(26,12);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(27,23);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(28,19);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(29,23);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(30,9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(31,14);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(32,11);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(33,4);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(34,9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(35,3);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(36,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(37,2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(40,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetBinContent(43,1);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetEntries(200);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetDirectory(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetStats(0);
   
   TF1 *chisqpdf2 = new TF1("chisqpdf","[0]*ROOT::Math::chisquared_pdf(x,[1])",0,250.7043, TF1::EAddToList::kNo);
   chisqpdf2->SetFillColor(19);
   chisqpdf2->SetFillStyle(0);
   chisqpdf2->SetMarkerStyle(20);
   chisqpdf2->SetLineColor(2);
   chisqpdf2->SetLineWidth(1);
   chisqpdf2->SetChisquare(25.34099);
   chisqpdf2->SetNDF(68);
   chisqpdf2->GetXaxis()->SetLabelFont(42);
   chisqpdf2->GetXaxis()->SetLabelOffset(0.007);
   chisqpdf2->GetXaxis()->SetLabelSize(0.05);
   chisqpdf2->GetXaxis()->SetTitleSize(0.06);
   chisqpdf2->GetXaxis()->SetTitleOffset(0.9);
   chisqpdf2->GetXaxis()->SetTitleFont(42);
   chisqpdf2->GetYaxis()->SetLabelFont(42);
   chisqpdf2->GetYaxis()->SetLabelOffset(0.007);
   chisqpdf2->GetYaxis()->SetLabelSize(0.05);
   chisqpdf2->GetYaxis()->SetTitleSize(0.06);
   chisqpdf2->GetYaxis()->SetTitleOffset(1.25);
   chisqpdf2->GetYaxis()->SetTitleFont(42);
   chisqpdf2->SetParameter(0,716.2739);
   chisqpdf2->SetParError(0,50.64822);
   chisqpdf2->SetParLimits(0,0,0);
   chisqpdf2->SetParameter(1,96.40293);
   chisqpdf2->SetParError(1,0.9767618);
   chisqpdf2->SetParLimits(1,0,0);
   chisqpdf2->SetParent(goodness_saturated_card_rhalphabet_all_2016_floatZhist__3);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetListOfFunctions()->Add(chisqpdf2);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetLineStyle(0);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->SetMarkerStyle(20);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetTitle("-2log#lambda");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetTitleOffset(0.9);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetXaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetTitle("Pseudodatasets");
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetTitleOffset(0.85);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetYaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetZaxis()->SetLabelFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetZaxis()->SetLabelOffset(0.007);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetZaxis()->SetLabelSize(0.05);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetZaxis()->SetTitleSize(0.06);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->GetZaxis()->SetTitleFont(42);
   goodness_saturated_card_rhalphabet_all_2016_floatZhist__3->Draw("pezsame");
   TArrow *arrow = new TArrow(117.7068,5.75,117.7068,0,0.05,">");
   arrow->SetFillColor(1);
   arrow->SetFillStyle(1001);

   ci = TColor::GetColor("#0000cc");
   arrow->SetLineColor(ci);
   arrow->SetLineWidth(2);
   arrow->Draw();
   
   TLegend *leg = new TLegend(0.6,0.6,0.89,0.89,NULL,"brNDC");
   leg->SetLineColor(0);
   leg->SetLineStyle(1);
   leg->SetLineWidth(0);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("goodness_saturated_card_rhalphabet_all_2016_floatZhist","toy data","lep");
   entry->SetLineColor(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("TArrow","observed = 117.7","l");

   ci = TColor::GetColor("#0000cc");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("goodness_saturated_card_rhalphabet_all_2016_floatZhist","p-value = 0.09","f");

   ci = TColor::GetColor("#00ccff");
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#00ccff");
   entry->SetLineColor(ci);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("chisqpdf","#chi^{2} fit, ndf = 96.4 #pm 1.0","l");
   entry->SetLineColor(2);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   TLatex *   tex = new TLatex(0.12,0.91,"CMS");
tex->SetNDC();
   tex->SetTextSize(0.06);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.23,0.91,"Preliminary");
tex->SetNDC();
   tex->SetTextFont(52);
   tex->SetLineWidth(2);
   tex->Draw();
      tex = new TLatex(0.76,0.91,"35.5 fb^{-1}");
tex->SetNDC();
   tex->SetTextFont(42);
   tex->SetLineWidth(2);
   tex->Draw();
   goodness_saturated_card_rhalphabet_all_2016_floatZ->Modified();
   goodness_saturated_card_rhalphabet_all_2016_floatZ->cd();
   goodness_saturated_card_rhalphabet_all_2016_floatZ->SetSelected(goodness_saturated_card_rhalphabet_all_2016_floatZ);
}
